# Generated by Django 2.2.4 on 2019-10-02 08:06

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0002_auto_20191002_1336'),
    ]

    operations = [
        migrations.CreateModel(
            name='price_calculate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('weight', models.FloatField()),
                ('price', models.IntegerField()),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 8, 6, 26, 254438, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 8, 6, 26, 252439, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 8, 6, 26, 250439, tzinfo=utc)),
        ),
    ]
