# Generated by Django 2.2.4 on 2019-10-02 10:05

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_auto_20191002_1336'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 10, 5, 3, 776434, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 10, 5, 3, 775434, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='username',
            field=models.CharField(max_length=50),
        ),
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 2, 10, 5, 3, 773434, tzinfo=utc)),
        ),
    ]
