# Generated by Django 2.2.4 on 2019-10-03 17:22

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0004_auto_20191002_1535'),
    ]

    operations = [
        migrations.CreateModel(
            name='cake',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cake_name', models.CharField(max_length=90)),
            ],
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 17, 22, 13, 136800, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 17, 22, 13, 135805, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 17, 22, 13, 133801, tzinfo=utc)),
        ),
    ]
