# Generated by Django 2.2.4 on 2019-10-03 18:02

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_auto_20191003_2252'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cake',
            name='id',
        ),
        migrations.AlterField(
            model_name='cake',
            name='cake_name',
            field=models.CharField(max_length=90, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='feedback',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 18, 2, 51, 756987, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='order',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 18, 2, 51, 755989, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='user',
            name='timestamp',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 3, 18, 2, 51, 753988, tzinfo=utc)),
        ),
    ]
